name: PHP Composer

on:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Deploy to <your domain>
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 144.91.118.151
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /var/www/html && ./server_deploy.sh'
